INSERT INTO TRAINEE (firstname, secondname) VALUES ('Michael', 'Massey')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Jarad', 'Huggard')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Daryl', 'Conway')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Sam', 'Kirk')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Hussein', 'Tejan')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Oliver', 'Loades')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Rachel', 'Lowe')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Benny', 'Wong')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Daniel', 'Osagie')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('George', 'Timbrell')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Ahmed', 'Syed')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Adam', 'Afzal')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Nawid', 'Mujadidi')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Christopher', 'Darrall')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Ekaterina', 'Genova')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Shiyamalan', 'Sunthar')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Zakariya', 'Mohamed')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Satwant', 'Birdi')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Jevale', 'Sterling')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Andrew', 'Freitas')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Liam', 'Donoghue')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Tibor', 'Gazsovics')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Naomi', 'Stanley')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Edward', 'Reynolds')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Anmar', 'Al-Qutayri')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('James', 'Thompson')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Nathan', 'Ahrens')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Arwa', 'Tawawala')
INSERT INTO TRAINEE (firstname, secondname) VALUES ('Mehul', 'Mepani')

INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?', 1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','4',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','4',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','3',1)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','4',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','4',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','4',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','4',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','3',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','4',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','3',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',2)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','4',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','3',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','4',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','5',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',3)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','4',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','4',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',4)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','4',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','4',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','4',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','5',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',5)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',6)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',7)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','4',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',8)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','4',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',9)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',10)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',11)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','4',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','0',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','none',12)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','4',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',13)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',14)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','4',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','5',15)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','4',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','4',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',16)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',17)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',18)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',19)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',20)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','5',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','4',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','3',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','4',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',21)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','5',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','5',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','4',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','5',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','3',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','5',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','3',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',22)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','4',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','4',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','4',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','4',23)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',24)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',25)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',26)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',27)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',28)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Agile','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java SE','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Databases','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Javascript','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Continuous Integration','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Automated Testing','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Python','?',29)
INSERT INTO SUBJECT (subjectname, subjectscore, trainee_id) VALUES ('Java EE','?',29)
